# -*- coding: utf-8 -*-
"""01_EDA_and_Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMtJd6EA0S5evOBR52HCkF9Gsr8YR9RD
"""

# 01 - EDA and Embeddings
## AI Powered Research Paper Intelligence System
### This notebook loads the dataset, cleans it, generates embeddings and saves everything to disk.

!pip install datasets sentence-transformers pandas numpy matplotlib

from datasets import load_dataset

print("Loading dataset...")
dataset = load_dataset("CShorten/ML-ArXiv-Papers", split="train")
print("Done!", dataset)

import pandas as pd

df = pd.DataFrame(dataset)
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

df = df[['title', 'abstract']]
df = df.head(15000)
print("Shape after trim:", df.shape)

print("Null values:")
print(df.isnull().sum())

df = df.dropna(subset=['title', 'abstract'])
print("Shape after dropping nulls:", df.shape)

df["paper_text"] = df["title"] + " " + df["abstract"]
df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
df["paper_text"] = df["paper_text"].str.strip()
print("paper_text column created!")
df[["title", "paper_text"]].head()

import matplotlib.pyplot as plt

df["word_count"] = df["abstract"].apply(lambda x: len(x.split()))

print("Average words:", df["word_count"].mean().round(2))
print("Max words:", df["word_count"].max())
print("Min words:", df["word_count"].min())

df["word_count"].hist(bins=50, color="steelblue", edgecolor="black")
plt.title("Distribution of Abstract Word Counts")
plt.xlabel("Word Count")
plt.ylabel("Number of Papers")
plt.tight_layout()
plt.show()

from collections import Counter
import re

all_words = " ".join(df["title"].tolist()).lower()
all_words = re.sub(r"[^a-z\s]", "", all_words)
word_list = all_words.split()

stopwords = {"a","an","the","of","in","for","on","with","and","to","is",
             "are","using","based","via","from","by","as","at","we","our",
             "this","that","be","its","via","towards"}

filtered = [w for w in word_list if w not in stopwords and len(w) > 2]
common = Counter(filtered).most_common(20)
words, counts = zip(*common)

plt.figure(figsize=(12, 5))
plt.bar(words, counts, color="coral", edgecolor="black")
plt.xticks(rotation=45, ha="right")
plt.title("Top 20 Most Common Words in Paper Titles")
plt.tight_layout()
plt.show()

# Extract year from abstract if mentioned
df["year"] = df["abstract"].str.extract(r'(20[0-2][0-9])')
year_counts = df["year"].value_counts().sort_index()

plt.figure(figsize=(10, 4))
plt.bar(year_counts.index, year_counts.values, color="mediumseagreen", edgecolor="black")
plt.title("Papers Mentioning Each Year")
plt.xlabel("Year")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

from sentence_transformers import SentenceTransformer

print("Loading model...")
model = SentenceTransformer("all-MiniLM-L6-v2")
print("Model loaded!")
print(type(model))

sample = df["paper_text"].iloc[0]
embedding = model.encode(sample)
print("Shape:", embedding.shape)
print("Type:", type(embedding))
print("Sample values:", embedding[:5])

import numpy as np

print("Generating embeddings for all papers...")
embeddings = model.encode(
    df["paper_text"].tolist(),
    batch_size=32,
    show_progress_bar=True
)
print("Embeddings shape:", embeddings.shape)

import os
os.makedirs("data", exist_ok=True)

np.save("data/arxiv_embeddings.npy", embeddings)
df.to_csv("data/cleaned_papers.csv", index=False)
print("✅ Embeddings saved to data/arxiv_embeddings.npy")
print("✅ DataFrame saved to data/cleaned_papers.csv")