# -*- coding: utf-8 -*-
"""02_Searcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1stSwDtq90aP8Dt0n3b4RpO6KY9ean8

# 02 - Searcher
## Loads FAISS index and performs semantic search on research papers.
### Features: Basic Search, Multi Query Search, Threshold Search
"""

!pip install faiss-cpu sentence-transformers pandas numpy

import pandas as pd
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer

df = pd.read_csv("data/cleaned_papers.csv")
embeddings = np.load("data/arxiv_embeddings.npy")
model = SentenceTransformer("all-MiniLM-L6-v2")

print("✅ Data loaded! Shape:", df.shape)
print("✅ Embeddings shape:", embeddings.shape)

import os

index_path = "data/paper_faiss.index"

if os.path.exists(index_path):
    print("Loading existing FAISS index...")
    index = faiss.read_index(index_path)
else:
    print("Building new FAISS index...")
    faiss_embeddings = embeddings.copy()
    faiss.normalize_L2(faiss_embeddings)
    index = faiss.IndexFlatIP(384)
    index.add(faiss_embeddings)
    faiss.write_index(index, index_path)
    print("✅ FAISS index saved!")

print("Total papers in index:", index.ntotal)

def search_papers(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)

    results = []
    print(f"\n🔍 Query: '{query}'\n")
    print("-" * 60)

    for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1):
        title = df.iloc[idx]["title"]
        abstract = df.iloc[idx]["abstract"][:300]
        print(f"#{rank} Score: {score:.4f}")
        print(f"    Title: {title}")
        print(f"    Preview: {abstract}...")
        print()
        results.append({
            "rank": rank,
            "score": round(float(score), 4),
            "title": title,
            "abstract": df.iloc[idx]["abstract"],
            "idx": int(idx)
        })

    return results

results = search_papers("deep learning for medical image analysis")

def multi_query_search(query1, query2, k=5):
    print("=" * 70)
    print(f"QUERY 1: '{query1}'")
    print("=" * 70)
    r1 = search_papers(query1, k)

    print("=" * 70)
    print(f"QUERY 2: '{query2}'")
    print("=" * 70)
    r2 = search_papers(query2, k)

    # Find overlapping papers
    idx1 = set([r["idx"] for r in r1])
    idx2 = set([r["idx"] for r in r2])
    overlap = idx1.intersection(idx2)

    print(f"\n📊 Papers appearing in BOTH queries: {len(overlap)}")
    if overlap:
        for idx in overlap:
            print(f"   → {df.iloc[idx]['title']}")

    return r1, r2

r1, r2 = multi_query_search(
    "transformer models for NLP",
    "BERT for text classification"
)

def search_with_threshold(query, k=10, threshold=0.65):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)

    print(f"🔍 Query: '{query}'")
    print(f"📊 Showing only results with score > {threshold}\n")

    filtered = [(score, idx) for score, idx in zip(D[0], I[0]) if score >= threshold]

    if not filtered:
        print("❌ No results above threshold. Try lowering it.")
        return []

    results = []
    for rank, (score, idx) in enumerate(filtered, start=1):
        print(f"#{rank} ✅ Score: {score:.4f}")
        print(f"    Title: {df.iloc[idx]['title']}\n")
        results.append({
            "rank": rank,
            "score": round(float(score), 4),
            "title": df.iloc[idx]["title"],
            "abstract": df.iloc[idx]["abstract"],
            "idx": int(idx)
        })

    return results

search_with_threshold("reinforcement learning robotics", threshold=0.60)

import json

results = search_papers("deep learning medical imaging")
with open("data/search_results.json", "w") as f:
    json.dump(results, f, indent=2)

print("✅ Search results saved to data/search_results.json")





