# -*- coding: utf-8 -*-
"""03_Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JqArcDz09iLTvH9o7Nn7Su8UUzfx0Ahs

# 03 - Summarizer
## Uses BART model to summarize research paper abstracts.
"""

!pip install transformers pandas

import pandas as pd
import json

df = pd.read_csv("data/cleaned_papers.csv")

with open("data/search_results.json", "r") as f:
    search_results = json.load(f)

print("✅ Loaded!", len(search_results), "search results")

from transformers import pipeline

print("Loading summarizer model...")
summarizer = pipeline(
    "summarization",
    model="sshleifer/distilbart-cnn-12-6"
)
print("✅ Summarizer loaded!")
print(type(summarizer))

abstract = df.iloc[0]["abstract"]
print("Original abstract length:", len(abstract.split()), "words\n")

summary = summarizer(abstract, max_length=120, min_length=40, do_sample=False)
print("Summary:")
print(summary[0]["summary_text"])

def summarize_results(search_results):
    print("Summarizing top search results...\n")

    for result in search_results:
        abstract = result["abstract"]
        summary = summarizer(abstract, max_length=120, min_length=40, do_sample=False)
        result["summary"] = summary[0]["summary_text"]

        print(f"📄 #{result['rank']} {result['title']}")
        print(f"   Score: {result['score']}")
        print(f"   Summary: {result['summary']}")
        print()

    return search_results

search_results = summarize_results(search_results)

with open("data/summarized_results.json", "w") as f:
    json.dump(search_results, f, indent=2)

print("✅ Summarized results saved!")



