# -*- coding: utf-8 -*-
"""04_Keyword_Finder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sR_c8nVirSKslNn5DOIR2gDqR6XsMVcv

# 04 - Keyword Finder
## Uses KeyBERT to extract important keywords from research papers.
### Features: Single paper keywords, Ngrams, Stopword removal, Batch extraction
"""

!pip install keybert sentence-transformers pandas

import pandas as pd
import json
from sentence_transformers import SentenceTransformer

df = pd.read_csv("data/cleaned_papers.csv")

with open("data/summarized_results.json", "r") as f:
    results = json.load(f)

model = SentenceTransformer("all-MiniLM-L6-v2")
print("✅ Loaded!")

from keybert import KeyBERT

kw_model = KeyBERT(model=model)
print("✅ KeyBERT loaded!")
print(type(kw_model))

text = df.iloc[0]["abstract"]
print("Abstract preview:", text[:200], "\n")

keywords = kw_model.extract_keywords(text)
print("Basic keywords:")
for kw, score in keywords:
    print(f"  {kw:30s} → {score:.4f}")

keywords_ngram = kw_model.extract_keywords(
    text,
    keyphrase_ngram_range=(1, 3),
    stop_words="english",
    top_n=10
)
print("Keywords with ngrams:")
for kw, score in keywords_ngram:
    print(f"  {kw:30s} → {score:.4f}")

def extract_keywords(results):
    for result in results:
        abstract = result["abstract"]
        keywords = kw_model.extract_keywords(
            abstract,
            keyphrase_ngram_range=(1, 2),
            stop_words="english",
            top_n=5
        )
        kw_list = [kw for kw, _ in keywords]
        result["keywords"] = kw_list

        print(f"📄 {result['title']}")
        print(f"   Keywords: {kw_list}\n")

    return results

results = extract_keywords(results)

import matplotlib.pyplot as plt
from collections import Counter

all_kws = []
for r in results:
    all_kws.extend(r["keywords"])

common = Counter(all_kws).most_common(15)
words, counts = zip(*common)

plt.figure(figsize=(12, 5))
plt.bar(words, counts, color="mediumseagreen", edgecolor="black")
plt.xticks(rotation=45, ha="right")
plt.title("Top Keywords Across Search Results")
plt.tight_layout()
plt.show()

with open("data/keywords_results.json", "w") as f:
    json.dump(results, f, indent=2)

print("✅ Keywords saved!")