# -*- coding: utf-8 -*-
"""05_NER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egYHErDKQJf3kRj14COBllp5sghoFEhk

# 05 - Named Entity Recognition (NER)
## Extracts people, organizations, locations from research papers.
"""

!pip install spacy pandas
!python -m spacy download en_core_web_sm

import spacy
import pandas as pd
import json

nlp = spacy.load("en_core_web_sm")
df = pd.read_csv("data/cleaned_papers.csv")

with open("data/keywords_results.json", "r") as f:
    results = json.load(f)

print("✅ Loaded!")

text = df.iloc[0]["abstract"]
doc = nlp(text)

print("Entities found:\n")
for ent in doc.ents:
    print(f"  {ent.text:30s} → {ent.label_}")

def extract_entities(results):
    for result in results:
        doc = nlp(result["abstract"])

        entities = {
            "people": [],
            "organizations": [],
            "locations": [],
            "misc": []
        }

        for ent in doc.ents:
            if ent.label_ == "PERSON":
                entities["people"].append(ent.text)
            elif ent.label_ == "ORG":
                entities["organizations"].append(ent.text)
            elif ent.label_ in ["GPE", "LOC"]:
                entities["locations"].append(ent.text)
            else:
                entities["misc"].append(ent.text)

        # Remove duplicates
        for key in entities:
            entities[key] = list(set(entities[key]))

        result["entities"] = entities

        print(f"📄 {result['title']}")
        print(f"   👤 People: {entities['people']}")
        print(f"   🏢 Orgs: {entities['organizations']}")
        print(f"   📍 Locations: {entities['locations']}\n")

    return results

results = extract_entities(results)

import matplotlib.pyplot as plt
from collections import Counter

all_orgs = []
for r in results:
    all_orgs.extend(r["entities"]["organizations"])

common_orgs = Counter(all_orgs).most_common(10)

if common_orgs:
    orgs, counts = zip(*common_orgs)
    plt.figure(figsize=(10, 4))
    plt.bar(orgs, counts, color="royalblue", edgecolor="black")
    plt.xticks(rotation=45, ha="right")
    plt.title("Most Mentioned Organizations in Search Results")
    plt.tight_layout()
    plt.show()
else:
    print("No organizations found in these results")

with open("data/ner_results.json", "w") as f:
    json.dump(results, f, indent=2)

print("✅ NER results saved!")



