# -*- coding: utf-8 -*-
"""06_Topic_Trend_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AC4gYMeDSpBNywZlYYO-UPJ4PVnKl2Da

# 06 - Topic Trend Analysis
## Analyzes which research topics are most popular in the dataset.
"""

!pip install pandas matplotlib numpy

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

df = pd.read_csv("data/cleaned_papers.csv")
print("✅ Loaded!", df.shape)

topics = {
    "Deep Learning": ["deep learning", "neural network", "backpropagation"],
    "Computer Vision": ["image", "vision", "cnn", "detection", "segmentation"],
    "NLP": ["nlp", "language", "text", "bert", "translation", "sentiment"],
    "Reinforcement Learning": ["reinforcement", "reward", "agent", "policy"],
    "Generative AI": ["generative", "gan", "diffusion", "synthesis"],
    "Graph Learning": ["graph", "node", "edge", "gnn"],
    "Federated Learning": ["federated", "privacy", "distributed"],
    "Transformers": ["transformer", "attention", "self-attention"],
    "Object Detection": ["yolo", "detection", "bounding box", "object"],
    "Medical AI": ["medical", "clinical", "disease", "diagnosis", "health"]
}

topic_counts = {}

for topic, keywords in topics.items():
    count = 0
    for kw in keywords:
        count += df["paper_text"].str.contains(kw, case=False).sum()
    topic_counts[topic] = count

topic_counts = dict(sorted(topic_counts.items(), key=lambda x: x[1], reverse=True))

print("Topic Counts:")
for topic, count in topic_counts.items():
    print(f"  {topic:25s}: {count} papers")

plt.figure(figsize=(12, 5))
plt.bar(topic_counts.keys(), topic_counts.values(), color="darkorange", edgecolor="black")
plt.xticks(rotation=45, ha="right")
plt.title("Topic Frequency in 15,000 ArXiv Papers")
plt.ylabel("Number of Papers")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 8))
plt.pie(
    topic_counts.values(),
    labels=topic_counts.keys(),
    autopct="%1.1f%%",
    startangle=140
)
plt.title("Topic Distribution in Dataset")
plt.tight_layout()
plt.show()

df["year"] = df["abstract"].str.extract(r'(20[0-2][0-9])')

for topic, keywords in list(topics.items())[:3]:
    mask = df["paper_text"].str.contains("|".join(keywords), case=False)
    year_counts = df[mask]["year"].value_counts().sort_index()

    plt.figure(figsize=(10, 3))
    plt.plot(year_counts.index, year_counts.values, marker="o", color="steelblue")
    plt.title(f"Year-wise Trend: {topic}")
    plt.xlabel("Year")
    plt.ylabel("Papers")
    plt.tight_layout()
    plt.show()

import pandas as pd

trend_df = pd.DataFrame(list(topic_counts.items()), columns=["Topic", "Count"])
trend_df.to_csv("data/trend_report.csv", index=False)
print("✅ Trend report saved!")