# -*- coding: utf-8 -*-
"""07_Deep_Learning_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Vvj4W5ap7Zfw06DN8UEIPeCWb06JX_H

# 07 - Deep Learning Classifier
## LSTM model to automatically classify research papers into topics.
"""

!pip install tensorflow pandas numpy scikit-learn matplotlib

import pandas as pd
import numpy as np

df = pd.read_csv("data/cleaned_papers.csv")
print("✅ Loaded!", df.shape)

def assign_topic(text):
    text = text.lower()
    if any(w in text for w in ["image", "vision", "cnn", "detection", "segmentation"]):
        return "Computer Vision"
    elif any(w in text for w in ["nlp", "language", "text", "bert", "translation"]):
        return "NLP"
    elif any(w in text for w in ["reinforcement", "reward", "agent", "policy"]):
        return "Reinforcement Learning"
    elif any(w in text for w in ["graph", "node", "edge", "gnn"]):
        return "Graph Learning"
    elif any(w in text for w in ["generative", "gan", "diffusion"]):
        return "Generative AI"
    elif any(w in text for w in ["federated", "privacy", "distributed"]):
        return "Federated Learning"
    else:
        return "General ML"

df["topic"] = df["paper_text"].apply(assign_topic)
print(df["topic"].value_counts())

import matplotlib.pyplot as plt

counts = df["topic"].value_counts()
plt.figure(figsize=(10, 5))
plt.bar(counts.index, counts.values, color="steelblue", edgecolor="black")
plt.xticks(rotation=30, ha="right")
plt.title("Paper Topic Distribution")
plt.tight_layout()
plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["label"] = le.fit_transform(df["topic"])
print("Classes:", le.classes_)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

MAX_WORDS = 10000
MAX_LEN = 200

tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token="<OOV>")
tokenizer.fit_on_texts(df["paper_text"].tolist())

sequences = tokenizer.texts_to_sequences(df["paper_text"].tolist())
padded = pad_sequences(sequences, maxlen=MAX_LEN, padding="post", truncating="post")

print("Padded shape:", padded.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    padded, df["label"].values,
    test_size=0.2,
    random_state=42
)

print("Train:", X_train.shape)
print("Test:", X_test.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional

num_classes = len(le.classes_)

model_lstm = Sequential([
    Embedding(input_dim=MAX_WORDS, output_dim=64, input_length=MAX_LEN),
    Bidirectional(LSTM(64, return_sequences=True)),
    Dropout(0.3),
    Bidirectional(LSTM(32)),
    Dropout(0.3),
    Dense(64, activation="relu"),
    Dense(num_classes, activation="softmax")
])

model_lstm.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

model_lstm.summary()

history = model_lstm.fit(
    X_train, y_train,
    epochs=5,
    batch_size=64,
    validation_data=(X_test, y_test)
)

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history["accuracy"], label="Train")
plt.plot(history.history["val_accuracy"], label="Val")
plt.title("Accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history["loss"], label="Train")
plt.plot(history.history["val_loss"], label="Val")
plt.title("Loss")
plt.legend()

plt.tight_layout()
plt.show()

loss, accuracy = model_lstm.evaluate(X_test, y_test)
print(f"✅ Test Accuracy: {accuracy*100:.2f}%")

def predict_topic(text):
    seq = tokenizer.texts_to_sequences([text])
    padded_seq = pad_sequences(seq, maxlen=MAX_LEN, padding="post")
    pred = model_lstm.predict(padded_seq)
    topic = le.classes_[np.argmax(pred)]
    confidence = np.max(pred) * 100
    print(f"📄 Predicted Topic: {topic}")
    print(f"🎯 Confidence: {confidence:.2f}%")
    return topic

predict_topic("This paper proposes a CNN for detecting tumors in MRI scans")

model_lstm.save("data/lstm_classifier.h5")
print("✅ Model saved!")