# -*- coding: utf-8 -*-
"""08_GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjygW2DhhmCuX1wMhe6GBZK6sAwT8RG7

# 08 - GenAI Intelligence Report
## Combines all results into one final intelligent report for any query.
### This is the final notebook that brings everything together.
"""

!pip install transformers sentence-transformers faiss-cpu pandas numpy spacy keybert
!python -m spacy download en_core_web_sm

import pandas as pd
import numpy as np
import faiss
import json
import spacy
from sentence_transformers import SentenceTransformer
from transformers import pipeline
from keybert import KeyBERT

# Load data
df = pd.read_csv("data/cleaned_papers.csv")
embeddings = np.load("data/arxiv_embeddings.npy")

# Load models
print("Loading models...")
search_model = SentenceTransformer("all-MiniLM-L6-v2")
summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")
kw_model = KeyBERT(model=search_model)
nlp = spacy.load("en_core_web_sm")

# Load FAISS
faiss_embeddings = embeddings.copy()
faiss.normalize_L2(faiss_embeddings)
index = faiss.IndexFlatIP(384)
index.add(faiss_embeddings)

print("✅ All models loaded!")

def intelligent_report(query, k=5):
    print(f"\n{'='*70}")
    print(f"🤖 AI RESEARCH INTELLIGENCE REPORT")
    print(f"Query: '{query}'")
    print(f"{'='*70}\n")

    # Step 1: Search
    query_embedding = search_model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)

    report = []

    for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1):
        title = df.iloc[idx]["title"]
        abstract = df.iloc[idx]["abstract"]

        # Step 2: Summarize
        summary = summarizer(abstract, max_length=100, min_length=30, do_sample=False)
        summary_text = summary[0]["summary_text"]

        # Step 3: Keywords
        keywords = kw_model.extract_keywords(
            abstract,
            keyphrase_ngram_range=(1, 2),
            stop_words="english",
            top_n=5
        )
        kw_list = [kw for kw, _ in keywords]

        # Step 4: NER
        doc = nlp(abstract)
        orgs = list(set([ent.text for ent in doc.ents if ent.label_ == "ORG"]))
        people = list(set([ent.text for ent in doc.ents if ent.label_ == "PERSON"]))

        # Print result
        print(f"📄 #{rank} | Score: {score:.4f}")
        print(f"   Title    : {title}")
        print(f"   Summary  : {summary_text}")
        print(f"   Keywords : {kw_list}")
        print(f"   Orgs     : {orgs[:3]}")
        print(f"   People   : {people[:3]}")
        print()

        report.append({
            "rank": rank,
            "score": round(float(score), 4),
            "title": title,
            "summary": summary_text,
            "keywords": kw_list,
            "organizations": orgs,
            "people": people
        })

    # Save report
    with open("data/final_report.json", "w") as f:
        json.dump({"query": query, "results": report}, f, indent=2)

    print("✅ Report saved to data/final_report.json")
    return report

report = intelligent_report("deep learning for medical image analysis")

report_df = pd.DataFrame(report)
report_df["keywords"] = report_df["keywords"].apply(lambda x: ", ".join(x))
report_df["organizations"] = report_df["organizations"].apply(lambda x: ", ".join(x))
report_df.to_csv("data/final_report.csv", index=False)
print("✅ Report also saved as CSV!")
report_df



